# Generated by Django 2.2.7 on 2019-11-11 16:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Block',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, unique=True)),
                ('title_origin', models.CharField(max_length=300, null=True)),
                ('language', models.CharField(max_length=300, null=True)),
                ('dialect', models.CharField(max_length=300, null=True)),
                ('theme', models.CharField(max_length=300, null=True)),
                ('place_of_recording', models.CharField(max_length=300, null=True)),
                ('time_of_recording', models.CharField(max_length=300, null=True)),
                ('publisher', models.CharField(max_length=300, null=True)),
                ('versions', models.CharField(max_length=300, null=True)),
                ('area_of_distribution', models.CharField(max_length=300, null=True)),
                ('initials', models.CharField(max_length=300, null=True)),
                ('text_preparation', models.CharField(max_length=300, null=True)),
                ('original_recording', models.CharField(max_length=300, null=True)),
                ('text_decipher', models.CharField(max_length=300, null=True)),
                ('translation', models.CharField(max_length=300, null=True)),
                ('manager', models.CharField(max_length=300, null=True)),
                ('commentary_preparation', models.CharField(max_length=300, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='annotation_tool.Class')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Description',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Не указано', max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Line',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.IntegerField(null=True)),
                ('text_right', models.CharField(default='Не указано', max_length=500)),
                ('text_left', models.CharField(default='Не указано', max_length=500)),
                ('block', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='annotation_tool.Block')),
            ],
            options={
                'unique_together': {('block', 'position')},
            },
        ),
        migrations.CreateModel(
            name='Relation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfileInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Не указано', max_length=80)),
                ('surname', models.CharField(default='Не указано', max_length=80)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TaggedItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
            ],
        ),
        migrations.CreateModel(
            name='Object',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('linked_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='annotation_tool.Class')),
            ],
        ),
        migrations.CreateModel(
            name='Phrase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('elements', models.CharField(max_length=20)),
                ('color', models.CharField(max_length=20)),
                ('line', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='annotation_tool.Line')),
            ],
            options={
                'unique_together': {('line', 'elements')},
            },
        ),
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='first_item', to='annotation_tool.TaggedItem')),
                ('relation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='annotation_tool.Relation')),
                ('second_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='second_item', to='annotation_tool.TaggedItem')),
            ],
            options={
                'unique_together': {('first_item', 'second_item')},
            },
        ),
    ]
