# Generated by Django 2.2.7 on 2019-11-19 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('annotation_tool', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='link',
            unique_together={('first_item', 'second_item', 'relation')},
        ),
    ]
