# Generated by Django 2.2.7 on 2019-12-04 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('annotation_tool', '0002_auto_20191120_0013'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='object',
            name='linked_class',
        ),
    ]
