# Generated by Django 2.2.7 on 2019-12-11 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annotation_tool', '0003_remove_object_linked_class'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='image',
            field=models.ImageField(default='images/default.png', null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='description',
            name='text',
            field=models.TextField(default='Не указано', max_length=500),
        ),
    ]
